import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Sign in | Nextjs Saas Starter kit",
  description: "Generated by create next app",
}

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className="flex items-center justify-center h-full min-h-screen">
      {children}
    </div>
  )
}
